### ISSUE TITLE
Username is not fetching..

### ISSUE THREAD

**Issue by mdanas13** [TufayelLUS/TikTok-Video-Downloader-PHP#1]
Username is not fetching with https://vm.tiktok.com/4o9AtF/ url.
Please fix it asap.
![n xczn ncxnjzkzflas](https://user-images.githubusercontent.com/47151696/79078182-0dada580-7d24-11ea-888d-e101eca2a71c.JPG)

**Comment by TufayelLUS** [comment]
Hi, thanks for pointing out the problem. It is now resolved and code is updated to support that.

**Comment by mdanas13** [comment]
It is not working

**Comment by TufayelLUS** [comment]
If you are trying to use it on demo server, it won't work. Upload the file in a server where php curl is supported. It will work for sure. Or you can deploy in your localhost.

**Comment by TufayelLUS** [comment]
Hi, I have retested everything on the server. It was the user agent issue and has been resolved. You can test with a new code now.

**Comment by TufayelLUS** [comment]
Sorry to say, I did a retest and found that TikTok short URL produces ReCaptcha check now. So it won't be possible to include both types of URLs. Please use regular direct URL format and it will work.
