### ISSUE TITLE
Watermark free broken for videos before July 27

### ISSUE THREAD

**Issue by davidteather** [TufayelLUS/TikTok-Video-Downloader-PHP#11]
Hey,
when you try to download videos before July 27th with the website the website url it sends you to responds with the following
```
{"status_code":0,"status_msg":"url doesn't match"}
```

**Comment by TufayelLUS** [comment]
Hi, I just noticed that the user agent plays an important role when the API is accessed. After applying a fix, it seems to work again. But there's still no solution for videos posted after and from July 27 but at least old videos are now downloading without watermark again.
Thanks for informing me. I was away for a bit.
