### ISSUE TITLE
authorization error when try to download 

### ISSUE THREAD

**Issue by MehdiMJ1** [TufayelLUS/TikTok-Video-Downloader-PHP#13]
Hi there , 
I have this web page when trying to download a video .. 

Access to v19-web.tiktokcdn.com was denied
You don't have authorization to view this page.
HTTP ERROR 403

Is that a geo restriction or something with the script , please help , thank you

**Comment by marcus99661** [comment]
Tiktok is now checking for referrer, you can check this https://github.com/drawrowfly/tiktok-scraper/issues/301

**Comment by TufayelLUS** [comment]
Thanks for your concern. Seems like there are HTTP referer issues as mentioned by @marcus99661 and adding referer did fix the watermark free downloader but seems like it won't work with normal(watermarked) videos. I will think about that later on.
