### ISSUE TITLE
Unable to find vid: string inside getKey response 

### ISSUE THREAD

**Issue by julitroalves** [TufayelLUS/TikTok-Video-Downloader-PHP#14]
Hi, thanks for your code, I guess the tiktok removed or changed vid: string from response of request video url:

After tested the following snipped I notice that "vid:" was not returned from tiktok url video api.
 
```
        $tmp = explode("vid:", $data);
        if (count($tmp) > 1) {
            return trim(explode("%", $tmp[1])[0]);
        }
```

Anyone already solved that problem?

**Comment by TufayelLUS** [comment]
This applies to videos after and from 27th July 2020. I didn't find any reliable and easy solution to this problem yet. As soon as one is found, it will be mentioned with changes. There is already one issue opened on this topic here #10 and so I am closing your issue as it will be followed on there.
