### ISSUE TITLE
Need your help please

### ISSUE THREAD

**Issue by Zhareiv** [TufayelLUS/TikTok-Video-Downloader-PHP#18]
Hello friend, I hope and you are very well.
I see that you are very good at what you do, that is why I request your support to review a code that I have, which is the same but has some "flaws", and I need the opinion of an expert.

I would like to talk to you, here is my email. game123727@gmail.com

**Comment by TufayelLUS** [comment]
Hey @Zhareiv, it is nice to have your response. Would you mind heading toward my Twitter account on [Click Here](https://twitter.com/cse_tufayel) for faster communication?
