### ISSUE TITLE
watermark not working?

### ISSUE THREAD

**Issue by sippinfreedom** [TufayelLUS/TikTok-Video-Downloader-PHP#21]

**Comment by TufayelLUS** [comment]
For newer videos from and after 27th July, 3030 won't download without a watermark, unfortunately.

**Comment by sippinfreedom** [comment]
> For newer videos from and after 27th July, 3030 won't download without a watermark, unfortunately.

gotcha, thank you.

**Comment by TufayelLUS** [comment]
You're welcome
