### ISSUE TITLE
Could not get/download tiktok videos

### ISSUE THREAD

**Issue by pratik-tech4** [TufayelLUS/TikTok-Video-Downloader-PHP#22]
Hi, @TufayelLUS 

i have tried your demo, but when i paste tiktok video url it always showing "please double check url", but my url is correct because in other website it is working like on [https://ssstik.io/](this website). 

Url i have tried 
[https://vm.tiktok.com/ganDYP/](https://vm.tiktok.com/ganDYP/)
[https://www.tiktok.com/@aqsadiary/video/6800561025209879809](https://www.tiktok.com/@aqsadiary/video/6800561025209879809)

Please help me.
Thanks in advance.

**Comment by TufayelLUS** [comment]
Hi, when my server is flagged temporarily as a bot, you will see this error. It gets fixed after some interval. I have no money to implement a proxied connection to the TikTok server to avoid a captcha trigger.
