### ISSUE TITLE
VM link is not working

### ISSUE THREAD

**Issue by MrBenFTW** [TufayelLUS/TikTok-Video-Downloader-PHP#26]
Hi, I think the code provided here is out of date because when I use a link vm.tiktok it does not work, but when I use the direct link it does.

However, when I use your own website, the VM link works. I think the code on the GitHub does not include the stuff for handling VM.tiktok but the one on your own server does. Could you update the GitHub repo please :)

**Comment by TufayelLUS** [comment]
Hi, it's the same code that I am using in my website backend. So, if it doesn't work, probably you are being returned with a captcha page from your IP/server IP when you are deploying the same code. If you plan to go commercial with this script, I will recommend you to use a rotating proxy service and integrate that in the code to overcome the captcha detection problem. Thank you.
