### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by letuan02** [TufayelLUS/TikTok-Video-Downloader-PHP#3]
Error: Please double check your url and try again.
Fix it for me please

**Comment by TufayelLUS** [comment]
Hi, please note that the allowed URL format is vm.tiktok.com/....(or similar short URL under tiktok domain only) and www.tiktok.com/@username/videoID
It does not accept any URL which is not under tiktok and does not accept any URL that is m.tiktok.com
Sorry for such limit, but please collect allowed video format and try again. 
You can try to copy link from desktop mode (browser has option change to desktop view) and then paste it correctly there. If the problem persists, please feel free to re-open the issue again.
