### ISSUE TITLE
CAn you please help me with url starting with vm.tiktok.com/

### ISSUE THREAD

**Issue by justinjean111** [TufayelLUS/TikTok-Video-Downloader-PHP#31]
Thanks a lot for your awesome work, it is amazing and fast, it works on PC but links generated by tiktok mobile that start with vm.tiktok does not work like this link https://vm.tiktok.com/ZMRqBxMsV/

I spent two days trying to fix it but I couldnt can you please help me fix this
thanks a lot

**Comment by TufayelLUS** [comment]
For the URLs of that type, when the URL redirects from one to another, it easily triggers the Recaptcha of TikTok. Therefore, it fails.
