### ISSUE TITLE
api2.musical.ly not working?

### ISSUE THREAD

**Issue by acedigibits** [TufayelLUS/TikTok-Video-Downloader-PHP#4]
not able to get watermark free video as api2.musical.ly does not give any response. is it down? any workaround?

**Comment by Inzilkin** [comment]
same thing

**Comment by TufayelLUS** [comment]
Thanks for informing the issue. Since this is the concern about api developer, we can wait for the api to come back online, or maybe I will keep looking for other ways around.

**Comment by Inzilkin** [comment]
Ok, waiting your fix for this problem :)

**Comment by Ayesh** [comment]
I'm fairly certain that the `api2.musical.ly` is gone for good, and one would need to use signed URLs to get the video download URLs.

**Comment by Inzilkin** [comment]
Is it possible in more detail about the signature of the link?

> I'm fairly certain that the `api2.musical.ly` is gone for good, and one would need to use signed URLs to get the video download URLs.

**Comment by TufayelLUS** [comment]
Yeah, seems like the developer of musically/TikTok has been notified about this and they planned to remove the API from public use. I will keep my eyes open to find some other ways around as currently, we do not have any such API at hand as backup other than that official old API.

**Comment by rifatozkancomtr** [comment]
Can you be an example?

http://v19.tiktokcdn.com/52ae54a7314f2c8101c3ec1076b3bd7f/5eee953e/video/tos/useast2a/tos-useast2a-ve-0068c004/e863392c2bbf4e2eb503213f2e2984cd/?a=1180&br=2216&bt=1108&cr=0&cs=0&dr=0&ds=6&er=&l=20200620170054010115069030074605E9&lr=tiktok&mime_type=video_mp4&qs=0&rc=anRsdW92cXFzdDMzNjczM0ApO2c2Njs3Zjs7NzY2O2Y3O2dhMWkuajMwY3FfLS0tMTZzczBgYWIzMDE2Y2NgMy5gNGM6Yw%3D%3D&vl=&vr=

**Comment by Ayesh** [comment]
That's the video URL, not the one that gives this video URL. 
https://tiktokoff.com, this site is still working with the watermark-less videos. 

TikTok is quickly detecting the `api2.musical.ly` access, and you all will need to use signed URLs with `verifyFp` and `signature` parameters to properly access their APIs.

**Comment by aj37289** [comment]
how it will be fixed

**Comment by aj37289** [comment]
[tiktok downloader](https://tiktokbooz.com/)

**Comment by drdexter1989** [comment]
Any updates about this?

**Comment by notela** [comment]
Some sites still work how they did it

**Comment by dutchtom91** [comment]
You can use https://api.tiktokv.com/aweme/v1/playwm/?video_id=$videoKey if you want a watermark free video.

**Comment by TufayelLUS** [comment]
Thank you very much @dutchtom91 for the API. It seems to work, but sometimes does not redirect to watermark-free videos. I added one more additional HTTP request from the server-side and the script will not reveal the conversion API anymore.
