### ISSUE TITLE
can't download the video, it shows it's forbidden.

### ISSUE THREAD

**Issue by hassanfaizm** [TufayelLUS/TikTok-Video-Downloader-PHP#40]
"contentURL" can be opened and played but when I try to download it, it shows "Failed - Forbidden".

**Comment by 89z** [comment]
please provide example URL

**Comment by hassanfaizm** [comment]
[https://v16-web.tiktok.com/video/tos/useast2a/tos-useast2a-ve-0068c003/78e35cbb28164d188115e2fb999a99d1/?a=1988&br=2380&bt=1190&cd=0%7C0%7C1%7C0&ch=0&cr=0&cs=0&cv=1&dr=0&ds=3&er=&expire=1647001010&ft=sd03~3Aonz7Thqx7VDXq&l=202203110615560102451411110F97703B&lr=tiktok_m&mime_type=video_mp4&net=0&pl=0&policy=3&qs=0&rc=M3A8Zjs6ZmVkOzMzNzczM0ApOmk7NmlmOWQ5N2Y5aTxmZ2dlNGRgcjQwZ2lgLS1kMTZzczBjXy82Yy8wMGNiYmAtX186Yw%3D%3D&signature=a284ff683d517f43f198956a7007d53d&tk=0&vl=&vr=](url)

**Comment by hassanfaizm** [comment]
https://v16-web.tiktok.com/video/tos/useast2a/tos-useast2a-pve-0068/6f40b8ced0714e02aa87bc19299bb0f7/?a=1988&br=4102&bt=2051&cd=0%7C0%7C1%7C0&ch=0&cr=0&cs=0&cv=1&dr=0&ds=3&er=&expire=1647001606&ft=sd03~3Aonz7ThBz7VDXq&l=202203110626260102510582202597FA05&lr=tiktok_m&mime_type=video_mp4&net=0&pl=0&policy=3&qs=0&rc=anU1ajQ6ZnduOzMzNzczM0ApZ2ZmZ2c7aWUzN2ZkPDNlZGdrZWBhcjRnLWRgLS1kMTZzczBeMC1hX2JjLzA1YDA0NDQ6Yw%3D%3D&signature=4c6c845908d3449ebd15f0ae5aabd8e4&tk=0&vl=&vr=

**Comment by 89z** [comment]
no, the public post URL

**Comment by hassanfaizm** [comment]
https://www.tiktok.com/@hankgreen1/video/7071004694751071494

**Comment by hassanfaizm** [comment]
https://www.tiktok.com/@hankgreen1/video/7075881489216392453

**Comment by pedrosaartes** [comment]
When we click on the download button without watermark, the code with error is displayed like this:

https://api2-16-h2.musical.ly/aweme/v1/play/?video_id=&vr_type=0&is_play_url=1&source=PackSourceEnum_PUBLISH&media_type=4

**Comment by TufayelLUS** [comment]
The forbidden problem appears if the request made from your browser doesn't contain the referer of the original video link. I have modified the code now and should download the video without errors as I locally tested it as working. The result may vary depending on the server. And the watermark free feature isn't available because there's no free API available to get that version of the video. Thank you for your consideration.
