### ISSUE TITLE
Still not working

### ISSUE THREAD

**Issue by sagitafb** [TufayelLUS/TikTok-Video-Downloader-PHP#41]
I have tried 5 times to download this video https://vt.tiktok.com/ZSRUhfvVv/
![Screenshot_2022-08-29-16-36-33-169_com android chrome](https://user-images.githubusercontent.com/83864721/187172558-4123a7fb-a229-4e77-ae6a-4198b09a8aed.jpg)

**Comment by TufayelLUS** [comment]
Updated with the latest TikTok website source code now. Should be working again.
