### ISSUE TITLE
Not able to download no watermark videos

### ISSUE THREAD

**Issue by ICommandMachinesObey** [TufayelLUS/TikTok-Video-Downloader-PHP#43]
I am not able to download no watermark videos I get this json output : {"status_code":5,"status_msg":"Invalid parameters","log_pb":{"impr_id":"20230227150345A1405083582C8729C84D"}}, but the watermark video works

**Comment by TufayelLUS** [comment]
Hi, the watermark-free API is not currently available, and that's why it's not working. If I find any free-to-use and easy-to-implement API for such cases in the future, I'll add it there.
