### ISSUE TITLE
Error at Line 90 index.php "Invalid Characters"

### ISSUE THREAD

**Issue by don2y** [TufayelLUS/TikTok-Video-Downloader-PHP#46]
Sir I found Error at line 90 index.php

Warning: curl_setopt_array(): Curl option contains invalid characters (\0) in C:\xampp\htdocs\tiktokd\index.php on line 90

**Comment by TufayelLUS** [comment]
Hi, as per my research on google with the same error mentioned, restarting apache might help to fix this issue. It's nothing with the code I believe. Kindly search this error on google and follow the troubleshoot articles to see if that gets fixed. Thank you.
