### ISSUE TITLE
BUG URL

### ISSUE THREAD

**Issue by NicolaszHD** [TufayelLUS/TikTok-Video-Downloader-PHP#49]
![Screenshot 2024-04-22 102348](https://github.com/TufayelLUS/TikTok-Video-Downloader-PHP/assets/19240740/16c5123f-c10a-4c8f-ae54-904c836fd9e1)

**Comment by TufayelLUS** [comment]
Thank you for letting me know. Fixes have been applied. Please try the new version and should be good to go again.
