### ISSUE TITLE
if we add anything inside <body> tag then it not work

### ISSUE THREAD

**Issue by kartik-jobs** [TufayelLUS/TikTok-Video-Downloader-PHP#6]
if we add anything inside <body> tag then it not work

**Comment by TufayelLUS** [comment]
Hi @kartik-jobs,
This is using HTML and PHP language. If you are doing it correctly, there won't be any chance of code being broken. Kindly take care of proper modification rules and there should not be any errors. Thanks.

**Comment by kartik-jobs** [comment]
I want to add snippet code in body tag but after adding that it don't work

**Comment by TufayelLUS** [comment]
If your snippet code is correct, it must work. If you are trying to embed my whole code into wordpress or any other CMS, that's not the correct place to do it. This script requires a PHP supported web hosting and must be placed in somewhere that supports php execution.
